// This file is auto-generated by @hey-api/openapi-ts

export { type Options, postBulk, postDetails } from './sdk.gen';
export type { ClientOptions, MemberBulkActionFailureModel, MemberBulkActionRequestModel, MemberBulkActionResponseModel, MemberBulkActionType, MemberDetailsRequestModel, MemberDetailsResponseModel, PostBulkData, PostBulkErrors, PostBulkResponse, PostBulkResponses, PostDetailsData, PostDetailsErrors, PostDetailsResponse, PostDetailsResponses } from './types.gen';
