// This file is auto-generated by @hey-api/openapi-ts

export { type Options, postBulk } from './sdk.gen';
export type { ClientOptions, MemberBulkActionFailureModel, MemberBulkActionRequestModel, MemberBulkActionResponseModel, MemberBulkActionType, PostBulkData, PostBulkErrors, PostBulkResponse, PostBulkResponses } from './types.gen';
