// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44381/' | (string & {});
};

export type MemberBulkActionFailureModel = {
    id: string;
    name: null | string;
    reason: string;
};

export type MemberBulkActionRequestModel = {
    memberIds: Array<string>;
    action: MemberBulkActionType;
};

export type MemberBulkActionResponseModel = {
    succeeded: number;
    failed: Array<MemberBulkActionFailureModel>;
};

export type MemberBulkActionType = 'Unlock' | 'Approve' | 'Unapprove' | 'Delete';

export type MemberDetailsRequestModel = {
    memberIds: Array<string>;
};

export type MemberDetailsResponseModel = {
    id: string;
    groups: Array<string>;
    createDate: string;
};

export type PostBulkData = {
    body: MemberBulkActionRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/member-dashboard/api/v1/bulk';
};

export type PostBulkErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostBulkResponses = {
    /**
     * OK
     */
    200: MemberBulkActionResponseModel;
};

export type PostBulkResponse = PostBulkResponses[keyof PostBulkResponses];

export type PostDetailsData = {
    body: MemberDetailsRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/member-dashboard/api/v1/details';
};

export type PostDetailsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostDetailsResponses = {
    /**
     * OK
     */
    200: Array<MemberDetailsResponseModel>;
};

export type PostDetailsResponse = PostDetailsResponses[keyof PostDetailsResponses];
